version: '3'

services:
  spark-master:
    container_name: thrift
    image: apache/spark:3.5.0
    ports:
      - "7077:7077"
      - "9080:8080"
      - "10000:10000"
    volumes:
      - parquet:/data/parquet:ro
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    command: >
      /bin/bash -c "  
        /opt/spark/sbin/start-master.sh &&    
        sleep 5 &&    
        /opt/spark/sbin/start-thriftserver.sh --master spark://spark-master:7077 --hiveconf hive.server2.thrift.port=10000 --hiveconf hive.server2.thrift.bind.host=0.0.0.0 --hiveconf hive.server2.authentication=NOSASL --hiveconf hive.server2.enable.doAs=false &&
        tail -f /opt/spark/logs/spark--org.apache.spark.sql.hive.thriftserver.HiveThriftServer2-*.out
      "

  spark-worker-1:
    image: apache/spark:3.5.0
    depends_on:
      - spark-master
    ports:
      - "9081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
    volumes:
      - parquet:/data/parquet:ro
    command: >
      /bin/bash -c "
        /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /dev/null
      "

  spark-worker-2:
    image: apache/spark:3.5.0
    depends_on:
      - spark-master
    ports:
      - "9082:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
    volumes:
      - parquet:/data/parquet:ro
    command: >
      /bin/bash -c "
        /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /dev/null  
      "

volumes:
  parquet:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/parquet

